quickswap_project/quickswap/urls.py
from django.urls import path
from quickswap import views

app_name = 'quickswap'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('category/<category_name>/', views.CategoryView.as_view(), name='category'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('user/<username>/', views.ProfileView.as_view(), name='user'),
    path('saved_trades/', views.SavedTradesView.as_view(), name='saved_trades'),
    path('allusers/', views.AllUsersView.as_view(), name='allusers'),
    path('contactus/', views.ContactUsView.as_view(), name='contactus'),
    path('helpdesk/', views.HelpdeskView.as_view(), name='helpdesk'),
    path('add_trade/', views.add_trade, name='add_trade'),
    path('alltrades/', views.AllTradesView.as_view(), name='alltrades'),
    path('trade/<slug:trade_name_slug>', views.TradeView.as_view(), name='trade'),
    path('edit_trade/<slug:trade_name_slug>/', views.EditTradeView.as_view(), name='edit_trade'), 
	path('save_trade/', views.SaveTradeView.as_view(), name='save_trade'),
    path('usertrades/<username>/', views.UserTradesView.as_view(), name='usertrades'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
]

quickswap_project/quickswap_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from quickswap import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
#from quickswap.regbackend import MyRegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('quickswap:register_profile')

urlpatterns = [
    path('', views.home, name='home'),
    path('quickswap/', include('quickswap.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/',MyRegistrationView.as_view(),name='registration_register'),
    path('accounts/', include('registration.backends.default.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quickswap_project/quickswap/forms.py
from django import forms
from django.contrib.auth.models import User
from quickswap.models import  UserProfile, Trade, Comment, Pictures
from registration.forms import RegistrationForm


class TradeForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'size': '60'}), max_length = 128, help_text="Please give your trade a name, try to be informative!")
    category = forms.ChoiceField(choices = Trade.CATEGORY_CHOICES,help_text="Please choose a category for your item of trade.")
    quality = forms.ChoiceField(choices = Trade.QUALITY_CHOICES,help_text="Please choose a level of quality for your item of trade.")
    description = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":60}), help_text="Give your trade a description, let people know what it is and isn't!")
    suggested_trade = forms.CharField(widget=forms.Textarea(attrs={"rows":2, "cols":60}),max_length = 128, help_text="Help people know what you might want in return!")

    class Meta:
        model = Trade
        fields = ('name','category',
            'quality','description','suggested_trade', 'location',)
			
			
class EditTradeForm(forms.ModelForm):

	#name = None the name is a unique key, we kinda can't change it. We should instead have a unique id
	category = None
	quality = None
	description = None
	suggested_trade = None

	class Meta:
		model = Trade
		#fields = ('name','category','quality','description','suggested_trade','location',)
		fields = ('category','quality','description','suggested_trade','location',)
		
		
	def __init__(self, *args, **kwargs):
		trade = kwargs.pop('trade')
		super(EditTradeForm, self).__init__(*args, **kwargs)
		# self.fields['name'] = forms.CharField( 	widget=forms.TextInput(attrs={'size': '60'}), 
										# max_length = 128, 
										# help_text="Please give your trade a name, try to be informative!",
										# initial=trade.name
										# )
		self.fields['category'] = forms.ChoiceField(	choices = Trade.CATEGORY_CHOICES,
											help_text="Please choose a category for your item of trade.",
											initial=trade.category
											)
		self.fields['quality'] = forms.ChoiceField(	choices = Trade.QUALITY_CHOICES,
											help_text="Please choose a level of quality for your item of trade.",
											initial=trade.quality
											)
		self.fields['description'] = forms.CharField(	widget=forms.Textarea(attrs={"rows":4, "cols":60}), 
											help_text="Give your trade a description, let people know what it is and isn't!", 
											initial=trade.description
											)
		self.fields['suggested_trade'] = forms.CharField(	widget=forms.Textarea(attrs={"rows":2, "cols":60}),
												max_length = 128, 
												help_text="Help people know what you might want in return!", 
												initial=trade.suggested_trade
												)


class PictureForm(forms.ModelForm):
    #this does not have helptext as it will display it for each input
    picture = forms.ImageField(label='Image', required = True)

    class Meta:
        model = Pictures
        fields = ('picture',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('description', 'picture',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'picture')

quickswap_project/quickswap/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from quickswap.models import Trade, Comment, Pictures
from quickswap.forms import UserForm, UserProfileForm, TradeForm, EditTradeForm, CommentForm, PictureForm
from datetime import datetime
from django.contrib.auth.models import User
from quickswap.models import UserProfile
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.views.generic.edit import DeleteView
from django.forms import modelformset_factory
from django.contrib import messages
from django.db.models import Count
import datetime
from django.utils import timezone

def home(request):

    #This check fixes the use case that a new superuser has logged in and been
    # redirected to the home page, where an error will occur displaying their profile
    # picture as a UserProfile object is not created with the superuser. This checks
    # the user is logged in by checking their username is not an empty string as it
    # is with anonymous users, and then creates the user profile if there isn't one
    # associated with the current user.
    if request.user.username != '':
        UserProfile.objects.get_or_create(user = request.user)
    #Used to filter most commented trade by those made in last week, otherwise older
    #trqdes with large amounts of comments ehos item has already been traded may
    #remain on the front page despite being of no interest
    date = timezone.now() - datetime.timedelta(days=7)
    trades_by_comments = Trade.objects.filter(date_made__gte=date).annotate(
            num_comments=Count('comment')).order_by('-num_comments')[:5]
    trades_by_newest = Trade.objects.order_by('-date_made')[:5]

    context_dict = {}
    comment_dict = {}
    picture_dict = {}
    if trades_by_comments.count() != 0:
        for trade in trades_by_comments:
            comment_dict[trade] = Comment.objects.filter(trade = trade).count()
            picture_dict[trade] = (Pictures.objects.filter(trade = trade).first()).picture

    context_dict['pictures'] = picture_dict
    context_dict['comment_num'] = comment_dict

    comment_dict = {}
    picture_dict = {}
    if trades_by_newest.count() != 0:
        for trade in trades_by_newest:
            comment_dict[trade] = Comment.objects.filter(trade = trade).count()
            picture_dict[trade] = (Pictures.objects.filter(trade = trade).first()).picture

    print(picture_dict)
    context_dict['pictures2'] = picture_dict
    context_dict['comment_num2'] = comment_dict

    context_dict['most_commented'] = trades_by_comments
    context_dict['most_recent'] = trades_by_newest

    return render(request, 'quickswap/home.html', context=context_dict)

def about(request):

    return render(request, 'quickswap/about.html')


@login_required
def add_trade(request):
    #user = request.user
    form = TradeForm()
    PictureFormSet = modelformset_factory(Pictures, form=PictureForm, extra=5, min_num=1)

    if request.method == 'POST':
        form = TradeForm(request.POST, request.FILES)
        formset = PictureFormSet(request.POST, request.FILES,
                               queryset=Pictures.objects.none())


        if form.is_valid() and formset.is_valid():
            trade = form.save(commit = False)
            trade.user = request.user
            trade.save()

            user = UserProfile.objects.get_or_create(user=request.user)[0]
            user.trades_made += 1
            user.save()


            for forms in formset.cleaned_data:
                #this helps to not crash if the user
                #do not upload all the photos
                if forms:
                    picture = forms['picture']
                    image = Pictures(trade=trade, picture=picture)
                    image.save()

            return redirect('quickswap:trade', trade.slug)
        else:
            print(form.errors, formset.errors)
    else:
        form = TradeForm()
        formset = PictureFormSet(queryset=Pictures.objects.none())
    return render(request, 'quickswap/add_trade.html', {'form': form, 'formset': formset})

@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('quickswap:home'))
        else:
            #context_dict['errors'] = form.errors
            print('An error occured:', form.errors)
    context_dict = {'form': form}
    return render(request, 'quickswap/profile_registration.html', context_dict)


class ProfileView(View):
	def get_user_details(self, username):
		try:
			user=User.objects.get(username=username)
		except User.DoesNotExist:
			return None

		user_profile = UserProfile.objects.get_or_create(user=user)[0]
		form = UserProfileForm({'description': user_profile.description,'picture': user_profile.picture})

		return(user, user_profile, form)


	@method_decorator(login_required)
	def get(self, request, username):
		try:
			(user, user_profile, form) = self.get_user_details(username)
		except TypeError:
			return redirect(reverse('quickswap:home'))
		
		trades = Trade.objects.filter(user = user)

		#This prevents a referenced before assignment error from dict
		picture_dict = {}
		comment_dict = {}
		if trades.count() != 0:
			for trade in trades:
				comment_dict[trade] = Comment.objects.filter(trade = trade).count()
				picture_dict[trade] =  (Pictures.objects.filter(trade = trade).first()).picture
		
			context_dict={'user_profile': user_profile,'selected_user': user,'trade_list': trades,'pictures':picture_dict, 'comment_num':comment_dict, 'form': form}
		
		else:
			context_dict={'user_profile': user_profile,'selected_user': user,'form': form}
		
		return render(request,'quickswap/user.html', context_dict)

	@method_decorator(login_required)
	def post(self, request, username):
		try:
			(user, user_profile, form) = self.get_user_details(username)
		except TypeError:
			return redirect(reverse('quickswap:home'))

		form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

		if form.is_valid():
			form.save(commit=True)
			return redirect('quickswap:user', user.username)
		else:
			print(form.errors)

		context_dict = {'user_profile': user_profile,'selected_user': user,'form': form}

		return render(request,'quickswap/user.html', context_dict)


class EditTradeView(View):
    def get_Trade_Details(self, trade_name_slug):
        try:
            trade = Trade.objects.get(slug=trade_name_slug)
        except Trade.DoesNotExist:
            return None
        pictures = Pictures.objects.filter(trade = trade)
        return(trade, pictures)


    @method_decorator(login_required)
    def get(self, request, trade_name_slug):
        try:
            (trade, pictures) = self.get_Trade_Details(trade_name_slug)
        except TypeError:
            return redirect(reverse('quickswap:home'))

        form = EditTradeForm(trade=trade)
        PictureFormSet = modelformset_factory(Pictures, form=PictureForm, extra=5, min_num=1)
        formset = PictureFormSet(queryset=Pictures.objects.none())

        context_dict = {'selected_trade':trade,
						'picture_list': pictures,
						'location1': trade.location[0],
						'location2': trade.location[1],
						'form':form,
						'formset': formset}

        return render(request, 'quickswap/edit_trade.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, trade_name_slug):
        try:
            (trade, pictures) = self.get_Trade_Details(trade_name_slug)
        except TypeError:
            return redirect(reverse('quickswap:home'))

        PictureFormSet = modelformset_factory(Pictures, form=PictureForm, extra=5, min_num=1)

        if request.method == 'POST':
            form = EditTradeForm(request.POST, request.FILES, trade=trade, instance=trade)
            formset = PictureFormSet(request.POST, request.FILES,
								   queryset=Pictures.objects.none())
            print(-1)

            if form.is_valid() and formset.is_valid():
                print(0)
                trade = form.save(commit = False)
                trade.user = request.user
                print(1)
                trade.save()
                print(2)

                user = UserProfile.objects.get_or_create(user=request.user)[0]
                user.save()
                print(3)


                for forms in formset.cleaned_data:
                    #this helps to not crash if the user
                    #do not upload all the photos
                    if forms:
                        picture = forms['picture']
                        image = Pictures(trade=trade, picture=picture)
                        image.save()

                return redirect('quickswap:trade', trade_name_slug)
            else:
                print(form.errors, formset.errors)
        else:
            form = EditTradeForm(trade=trade)
            formset = PictureFormSet(queryset=Pictures.objects.none())

        context_dict = {'selected_trade':trade,
				'picture_list': pictures,
				'location1': trade.location[0],
				'location2': trade.location[1],
				'form':form,
				'formset': formset}

        return render(request, 'quickswap/edit_trade.html', context_dict)


class TradeView(View):

    def get_Trade_Details(self, trade_name_slug):
        try:
            trade = Trade.objects.get(slug=trade_name_slug)
        except Trade.DoesNotExist:
            return None

        comments = Comment.objects.filter(trade = trade)
        pictures = Pictures.objects.filter(trade = trade)
        form = CommentForm()

quickswap_project/templates/quickswap/add_trade.html
{% extends 'quickswap/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block scripts/styles_block %}
  {% load mapbox_location_field_tags %}
  {% location_field_includes %}
  {% include_jquery %}
{% endblock %}

{% block title_block %}
    Add a Trade
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">New Trade</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <form role="form" id="trade_form" method="post" action="{% url 'quickswap:add_trade' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form }}
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">Add Trade</button>
            <div class="p-5"></div>
        </form>
        {{ form.media }}
    </div>
</div>
{% endblock %}

quickswap_project/templates/quickswap/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load quickswap_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/refresh.svg' %}">
    <title>
        Quickswap - {% block title_block %} Trade Today! {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    <!-- <link href="{% static "css/pro.css" %} rel="stylesheet" type="text/css"/> -->
    <link rel="stylesheet" href="/static/css/base.css" >
    {% block scripts/styles_block %}
    {% endblock %}
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'quickswap:home' %}">
                  Quickswap
                  <img src="{% static 'images/repeat.svg' %}" width="24" height="24" class="d-inline-block align-top">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'quickswap:home' %}">Home</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link"href="{% url 'quickswap:user' user.username %}">My Profile
                              {% if user.userprofile.picture %}
                                <img class="img-fluid rounded-circle" src="{{ MEDIA_URL }}{{ user.userprofile.picture }}"
                                   width="24"
                                   height="24">
                               {% endif %}
                               </a>
                            </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'quickswap:saved_trades' %}">Saved Trades</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'quickswap:add_trade' %}">New Trade</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/quickswap/">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link"href="{% url 'quickswap:categories' %}">Categories</a></li>
                        <li class="nav-item"><a class="nav-link"href="{% url 'quickswap:allusers' %}">All Users</a></li>
                        <li class="nav-item"><a class="nav-link"href="{% url 'quickswap:alltrades' %}">All Trades</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'quickswap:about' %}">About</a></li>
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container">
            <div class="row">

                <main role="main" class="col-md-12  ml-sm-auto col-lg-12 px-4">
                    {% block body_block %}{% endblock %}

                    <!-- FOOTER -->
                    <footer>
                        <p>&copy; 2020 Quickswap &middot; <a href="{% url 'quickswap:contactus' %}">Contact Us</a> &middot; <a href="{% url 'quickswap:helpdesk' %}">Helpdesk</a>
                        <p id="time"></p>
                    </footer>
                </main>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		    <script src="{% static "js/quickswap-ajax.js" %}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
		    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
        <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/base.js' %}"></script>
    </body>
</html>

quickswap_project/templates/quickswap/user.html
{% extends 'quickswap/base.html' %}
{% load quickswap_template_tags %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title_block %}
    Profile of {{ selected_user.username }}.
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
  <div class="container">
    <h1 class="jumbotron-heading">
      {% if selected_user == user %}
         Your profile
      {% else %}
        {{ selected_user.username }}'s Profile
        {% if selected_user.is_superuser %}
          - Admin
        {% endif %}
      {% endif %}
    </h1>
  </div>
</div>

<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link href="/static/css/usertrades.css" rel="stylesheet" >
	</head>

	<body>
		<div class="container">
			<div class="row">
				<div class="col">
					<img src="{{ MEDIA_URL }}{{ user_profile.picture }}"
						width="300"
						height="300"
						alt="{{ selected_user.username }}'s profile image"/>
				</div>
				<div class="col">
					<div>
						{% if selected_user == user %}
							<form method="post"action="."enctype="multipart/form-data">
								{% csrf_token %}
								{{ form | crispy }}

								<input class="btn btn-warning button-margin" type="submit"value="Update"/>
							</form>
							<a class="btn btn-primary button-margin" href="{% url 'quickswap:usertrades' selected_user.username %}">My Trades</a> <br />
							<a class="btn btn-danger button-margin" href="{% url 'auth_password_change' %}">Change Password</a>
						{% else %}
							{% if user_profile.description %}
								<p>
									Description: {{ user_profile.description }}
								</p>
							{% endif %}
							<br />
							<a class="btn btn-primary" href="{% url 'quickswap:usertrades' selected_user.username %}">Their Trades</a>
						{% endif %}
					</div>
				</div>
				<div class="col">
				  <p>
					Date Joined: <br />
					{{ selected_user.date_joined|date:"D - d/m/Y" }} <br />
					{{ selected_user.date_joined|timesince }} ago. <br />
					<br />
					Last Login:   {{ selected_user.last_login }}<br />
					{{ selected_user.last_login|date:"D - d/m/Y" }} <br />
					{{ selected_user.last_login|timesince }} ago. <br />
					<br />
					Trades made: {{ user_profile.trades_made }} <br />
					Comments made: {{ user_profile.comments_made }} <br />
				  </p>
				</div>
			</div>
			<br>
			<h3 class="divider">My trades: </h3>
			<div class="row">
				{% if trade_list %}
					{% for trade in trade_list %}
						<br>
						<div class="column">
							<div class="card">
								<a href="{% url 'quickswap:trade' trade.slug %}">
									<img class="usertrades-images" src="{{ MEDIA_URL }}{{ pictures|getDictValue:trade }}" alt="{{ trade.name }}">
								</a>
								<div class="container">	
									<h5 class="card_title">
										<a class="trade_name wrap-text" href="{% url 'quickswap:trade' trade.slug %}" > {{ trade.name }}  </a>
										{% if selected_user == user %}
											<a href="{% url 'quickswap:edit_trade' trade.slug %}"><i class="fa fa-pencil pencil-colour"></i></a>
										{% else %}
											<button id="button{{ forloop.counter }}"
													data-tradeName="{{ trade.name }}"
													data-user="{{ user }}"
													type="button"
											><i class="fa fa-heart"></i></button>
										{% endif %}
									</h5>
									<p>
										{{ trade.date_made|date:"jS F, Y" }}
									</p>
									<p class="overflow-ellipsis">
										{{ trade.description }}
									</p>
									<p>
										I'm looking for: {{ trade.suggested_trade }}
									</p>
									{% if selected_user != user %}
										<p><button class="disabled offer_trade_button" >Offer trade</button></p>
									{% endif %}
								</div>
							</div>
						</div>
					{% endfor %}
				{% else %}
					<h5>
					  You have not made any trades yet <img src="{% static 'images/frown.svg' %}"> <br />
					  <a href="{% url 'quickswap:add_trade' %}">Why don't you make one now?</a>
					</h5>
				{% endif %}
			</div>
		</div>
		
		<script src="{% static "js/save-button-user-ajax.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
		
	</body>
</html>
{% endblock %}

quickswap_project/templates/quickswap/usertrades.html
{% extends 'quickswap/home.html' %}
{% load quickswap_template_tags %}
{% load staticfiles %}

{% block title_block %}
  {{ user.username }}'s trades.
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
  <div class="container">
    {% if selected_user == user %}
      <h1 class="jumbotron-heading"> Your Trades </h1>
    {% else %}
      <h1 class="jumbotron-heading">{{ selected_user.username }}'s Trades</h1>
    {% endif %}
  </div>
</div>

<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link href="/static/css/usertrades.css" rel="stylesheet" >
	</head>

	<body>
		<div class="container">
			<div class="row">
				{% if trade_list %}
					{% for trade in trade_list %}
						<div class="column">
							<div class="card">
								<a href="{% url 'quickswap:trade' trade.slug %}">
									<img class="usertrades-images" src="{{ MEDIA_URL }}{{ pictures|getDictValue:trade }}" alt="{{ trade.name }}">
								</a>
								<div class="container">	
									<h5 class="card_title">
										<a class="trade_name wrap-text" href="{% url 'quickswap:trade' trade.slug %}" > {{ trade.name }}  </a>
										{% if selected_user == user %}
											<a href="{% url 'quickswap:edit_trade' trade.slug %}"><i class="fa fa-pencil pencil-colour"></i></a>
										{% else %}
											<button class="icon_button" id="save_button"><i class="fa fa-heart"></i></button>
											<a href="#"><i class="fa fa-flag"></i></a>  <!-- this should report the trade -->
										{% endif %}
									</h5>
									<p>
										{{ trade.date_made|date:"jS F, Y" }}
									</p>
									<p class="overflow-ellipsis">
										{{ trade.description }}
									</p>
									<p>
										I'm looking for: {{ trade.suggested_trade }}
									</p>
									{% if selected_user != user %}
										<p><button class="disabled offer_trade_button" >Offer trade</button></p>
									{% endif %}
								</div>
							</div>
						</div>
					{% endfor %}
				{% else %}
					<h5>
					  You have not made any trades yet <img src="{% static 'images/frown.svg' %}"> <br />
					  <a href="{% url 'quickswap:add_trade' %}">Why don't you make one now?</a>
					</h5>
				{% endif %}
			</div>
		</div>
		
	</body>
</html>

{% endblock %}